import type {
  Institution,
  InstitutionSettings,
  MagicLinkRequest,
  Person,
  TeamMember,
  VerificationRequest,
} from "./types";

export const mockInstitution: Institution = {
  id: "inst_northbridge",
  name: "Northbridge University",
  type: "University",
  website: "https://northbridge.edu",
  address: "12 College Green, Northbridge, NB 44021",
  primaryVerificationEmail: "verify@northbridge.edu",
  domain: "northbridge.edu",
  location: "Northbridge, NB",
  workEmail: "verify@northbridge.edu",
  verificationState: "verified",
  domainVerifiedAt: "2026-07-15T09:00:00Z",
};

export const mockTeam: TeamMember[] = [
  {
    id: "u_priya",
    name: "Priya Menon",
    email: "priya.menon@northbridge.edu",
    role: "owner",
    status: "active",
    lastActive: "2026-07-22T09:14:00Z",
  },
  {
    id: "u_daniel",
    name: "Daniel Okafor",
    email: "daniel.okafor@northbridge.edu",
    role: "admin",
    status: "active",
    lastActive: "2026-07-21T16:02:00Z",
  },
  {
    id: "u_hana",
    name: "Hana Suzuki",
    email: "hana.suzuki@northbridge.edu",
    role: "reviewer",
    status: "active",
    lastActive: "2026-07-22T11:32:00Z",
  },
  {
    id: "u_marcus",
    name: "Marcus Field",
    email: "marcus.field@northbridge.edu",
    role: "reviewer",
    status: "pending",
  },
  {
    id: "u_lena",
    name: "Lena Alvarez",
    email: "lena.alvarez@northbridge.edu",
    role: "reviewer",
    status: "suspended",
    lastActive: "2026-06-30T08:11:00Z",
  },
];

export const mockRequests: VerificationRequest[] = [
  {
    id: "req_001",
    reference: "KVR-2026-0421",
    candidateName: "Aarav Shah",
    candidateId: "p_aarav",
    requestedBy: "Helix Bio Labs",
    requestPurpose: "Employment verification — Senior Research Associate",
    requestingContact: "people@helixbio.com",
    status: "pending",
    receivedAt: "2026-07-20T10:12:00Z",
    dueAt: "2026-07-27T17:00:00Z",
    assignedTo: "Hana Suzuki",
    nextAction: "Review candidate claim",
    consentReceived: true,
    claim: {
      candidateName: "Aarav Shah",
      studentId: "NBU-2018-4421",
      institutionName: "Northbridge University",
      degree: "B.Sc. Biotechnology",
      programme: "Biotechnology (Hons.)",
      department: "School of Life Sciences",
      admissionYear: "2015",
      graduationYear: "2019",
      completionStatus: "Completed",
    },
    institutionRecord: {
      found: true,
      studentId: "NBU-2018-4421",
      officialName: "Aarav R. Shah",
      degree: "B.Sc. Biotechnology",
      programme: "Biotechnology (Hons.)",
      department: "School of Life Sciences",
      admissionDate: "2015-08-01",
      graduationDate: "2019-06-14",
      completionStatus: "Completed",
      credentialIssuanceStatus: "Issued",
    },
    matchStatus: "exact",
    fieldMatches: {
      "Student ID": "match",
      Degree: "match",
      Programme: "match",
      Department: "match",
      "Graduation year": "match",
      "Completion status": "match",
    },
    evidence: [
      {
        id: "e1",
        name: "Degree_Certificate.pdf",
        type: "Degree certificate",
        uploadedBy: "Aarav Shah",
        uploadedAt: "2026-07-20T10:11:00Z",
      },
    ],
    internalNotes: [],
    timeline: [
      { id: "t1", at: "2026-07-20T10:12:00Z", label: "Request received" },
      { id: "t2", at: "2026-07-20T10:13:00Z", label: "Consent confirmed" },
      { id: "t3", at: "2026-07-20T10:20:00Z", label: "Reviewer assigned", detail: "Hana Suzuki" },
      { id: "t4", at: "2026-07-20T10:21:00Z", label: "Record matched" },
    ],
  },
  {
    id: "req_002",
    reference: "KVR-2026-0418",
    candidateName: "Meera Iyer",
    candidateId: "p_meera",
    requestedBy: "Northlake Health System",
    requestPurpose: "Employment verification — Consultant Physician",
    status: "in_progress",
    receivedAt: "2026-07-18T08:45:00Z",
    dueAt: "2026-07-25T17:00:00Z",
    assignedTo: "Daniel Okafor",
    nextAction: "Compare graduation year",
    consentReceived: true,
    claim: {
      candidateName: "Meera Iyer",
      studentId: "NBU-2010-1122",
      institutionName: "Northbridge University",
      degree: "MBBS",
      programme: "Medicine",
      department: "School of Medicine",
      admissionYear: "2005",
      graduationYear: "2011",
      completionStatus: "Completed",
    },
    institutionRecord: {
      found: true,
      studentId: "NBU-2010-1122",
      officialName: "Meera S. Iyer",
      degree: "MBBS",
      programme: "Medicine",
      department: "School of Medicine",
      admissionDate: "2005-08-01",
      graduationDate: "2010-07-30",
      completionStatus: "Completed",
      credentialIssuanceStatus: "Issued",
    },
    matchStatus: "partial",
    fieldMatches: {
      "Student ID": "match",
      Degree: "match",
      Programme: "match",
      "Graduation year": "different",
      "Completion status": "match",
    },
    evidence: [
      {
        id: "e2",
        name: "MBBS_Transcript.pdf",
        type: "Transcript",
        uploadedBy: "Meera Iyer",
        uploadedAt: "2026-07-18T08:40:00Z",
      },
    ],
    internalNotes: [
      {
        id: "n1",
        author: "Daniel Okafor",
        createdAt: "2026-07-19T09:12:00Z",
        body: "Candidate lists 2011 graduation; our record shows 2010. Need to check convocation batch.",
      },
    ],
    timeline: [
      { id: "t1", at: "2026-07-18T08:45:00Z", label: "Request received" },
      { id: "t2", at: "2026-07-18T08:46:00Z", label: "Consent confirmed" },
      { id: "t3", at: "2026-07-18T09:00:00Z", label: "Reviewer assigned", detail: "Daniel Okafor" },
    ],
  },
  {
    id: "req_003",
    reference: "KVR-2026-0402",
    candidateName: "Jonas Weber",
    candidateId: "p_jonas",
    requestedBy: "Atlas Ventures",
    requestPurpose: "Due diligence — Portfolio company founder",
    status: "awaiting_clarification",
    receivedAt: "2026-07-14T13:22:00Z",
    assignedTo: "Hana Suzuki",
    nextAction: "Await candidate response",
    consentReceived: true,
    claim: {
      candidateName: "Jonas Weber",
      studentId: "NBU-2013-0091",
      institutionName: "Northbridge University",
      degree: "MBA",
      programme: "Executive MBA",
      department: "Northbridge Business School",
      admissionYear: "2012",
      graduationYear: "2014",
      completionStatus: "Completed",
    },
    institutionRecord: {
      found: false,
    },
    matchStatus: "record_unavailable",
    evidence: [],
    internalNotes: [
      {
        id: "n1",
        author: "Hana Suzuki",
        createdAt: "2026-07-15T10:00:00Z",
        body: "Requested clarification on student ID; possible name mismatch in older records.",
      },
    ],
    timeline: [
      { id: "t1", at: "2026-07-14T13:22:00Z", label: "Request received" },
      { id: "t2", at: "2026-07-14T13:24:00Z", label: "Consent confirmed" },
      { id: "t3", at: "2026-07-15T10:00:00Z", label: "Clarification requested" },
    ],
  },
  {
    id: "req_004",
    reference: "KVR-2026-0355",
    candidateName: "Sofia Marin",
    candidateId: "p_sofia",
    requestedBy: "Meridian Audit Partners",
    requestPurpose: "Employment verification — Senior Auditor",
    status: "confirmed",
    receivedAt: "2026-07-05T09:30:00Z",
    assignedTo: "Priya Menon",
    consentReceived: true,
    claim: {
      candidateName: "Sofia Marin",
      studentId: "NBU-2016-7781",
      institutionName: "Northbridge University",
      degree: "B.Com (Hons.)",
      programme: "Accounting & Finance",
      department: "Northbridge Business School",
      admissionYear: "2013",
      graduationYear: "2016",
      completionStatus: "Completed",
    },
    institutionRecord: {
      found: true,
      studentId: "NBU-2016-7781",
      officialName: "Sofia Marin",
      degree: "B.Com (Hons.)",
      programme: "Accounting & Finance",
      department: "Northbridge Business School",
      admissionDate: "2013-08-01",
      graduationDate: "2016-06-12",
      completionStatus: "Completed",
      credentialIssuanceStatus: "Issued",
    },
    matchStatus: "exact",
    evidence: [],
    internalNotes: [],
    timeline: [
      { id: "t1", at: "2026-07-05T09:30:00Z", label: "Request received" },
      { id: "t2", at: "2026-07-05T09:31:00Z", label: "Consent confirmed" },
      {
        id: "t3",
        at: "2026-07-05T11:15:00Z",
        label: "Verification confirmed",
        detail: "Priya Menon",
      },
    ],
  },
  {
    id: "req_005",
    reference: "KVR-2026-0300",
    candidateName: "Ravi Kulkarni",
    candidateId: "p_ravi",
    requestedBy: "Trellis Consulting",
    requestPurpose: "Employment verification",
    status: "discrepancy",
    receivedAt: "2026-06-28T14:10:00Z",
    assignedTo: "Daniel Okafor",
    consentReceived: true,
    claim: {
      candidateName: "Ravi Kulkarni",
      studentId: "NBU-2014-3320",
      institutionName: "Northbridge University",
      degree: "M.Tech Computer Science",
      programme: "Computer Science",
      department: "School of Engineering",
      admissionYear: "2012",
      graduationYear: "2014",
      completionStatus: "Completed",
    },
    institutionRecord: {
      found: true,
      studentId: "NBU-2014-3320",
      officialName: "Ravi Kulkarni",
      degree: "M.Tech Computer Science",
      programme: "Computer Science",
      department: "School of Engineering",
      admissionDate: "2012-08-01",
      completionStatus: "Withdrawn",
      credentialIssuanceStatus: "Not issued",
    },
    matchStatus: "partial",
    fieldMatches: {
      "Student ID": "match",
      Degree: "match",
      "Completion status": "different",
    },
    evidence: [],
    internalNotes: [],
    timeline: [
      { id: "t1", at: "2026-06-28T14:10:00Z", label: "Request received" },
      {
        id: "t2",
        at: "2026-06-29T09:00:00Z",
        label: "Discrepancy reported",
        detail: "Completion status differs",
      },
    ],
  },
  {
    id: "req_006",
    reference: "KVR-2026-0288",
    candidateName: "Elena Rossi",
    candidateId: "p_elena",
    requestedBy: "Bright Path Schools",
    requestPurpose: "Employment verification — Teacher",
    status: "pending",
    receivedAt: "2026-07-22T07:05:00Z",
    dueAt: "2026-07-29T17:00:00Z",
    nextAction: "Assign reviewer",
    consentReceived: true,
    claim: {
      candidateName: "Elena Rossi",
      studentId: "NBU-2017-6612",
      institutionName: "Northbridge University",
      degree: "B.Ed.",
      programme: "Elementary Education",
      department: "School of Education",
      admissionYear: "2014",
      graduationYear: "2017",
      completionStatus: "Completed",
    },
    institutionRecord: {
      found: true,
      studentId: "NBU-2017-6612",
      officialName: "Elena Rossi",
      degree: "B.Ed.",
      programme: "Elementary Education",
      department: "School of Education",
      admissionDate: "2014-08-01",
      graduationDate: "2017-06-15",
      completionStatus: "Completed",
      credentialIssuanceStatus: "Issued",
    },
    matchStatus: "exact",
    evidence: [],
    internalNotes: [],
    timeline: [{ id: "t1", at: "2026-07-22T07:05:00Z", label: "Request received" }],
  },
];

export const mockPeople: Person[] = [
  {
    id: "p_aarav",
    name: "Aarav Shah",
    institutionStatus: "alumni",
    trustStatus: "institution_verified",
    passportStatus: "connected",
    degree: "B.Sc. Biotechnology",
    graduationYear: "2019",
    relationship: {
      institutionName: "Northbridge University",
      studentId: "NBU-2018-4421",
      status: "alumni",
      degree: "B.Sc. Biotechnology",
      programme: "Biotechnology (Hons.)",
      department: "School of Life Sciences",
      admissionPeriod: "Aug 2015",
      graduationPeriod: "Jun 2019",
      verificationStatus: "institution_verified",
    },
    sharedProfile: {
      consented: true,
      currentTitle: "Senior Research Associate",
      currentCompany: "Helix Bio Labs",
      industry: "Biotechnology",
      location: "Boston, MA",
      credentials: [],
      lastUpdated: "2026-06-10T00:00:00Z",
    },
    credentials: [
      {
        id: "c1",
        name: "B.Sc. Biotechnology — Degree",
        status: "verified",
        issueDate: "2019-06-30",
        lastUpdated: "2019-06-30",
        history: [{ at: "2019-06-30", label: "Issued" }],
      },
      {
        id: "c2",
        name: "Official Transcript",
        status: "verified",
        issueDate: "2019-07-10",
        lastUpdated: "2019-07-10",
        history: [{ at: "2019-07-10", label: "Issued" }],
      },
    ],
    verificationActivity: [
      {
        id: "va1",
        requestingOrg: "Helix Bio Labs",
        date: "2026-07-20",
        result: "In review",
        reviewer: "Hana Suzuki",
        status: "pending",
        requestId: "req_001",
      },
    ],
    timeline: [
      { id: "t1", at: "2015-08-01", label: "Person connected to institution" },
      { id: "t2", at: "2019-06-30", label: "Education verified" },
    ],
    lastUpdated: "2026-06-10",
  },
  {
    id: "p_meera",
    name: "Meera Iyer",
    institutionStatus: "alumni",
    trustStatus: "institution_verified",
    passportStatus: "connected",
    degree: "MBBS",
    graduationYear: "2010",
    relationship: {
      institutionName: "Northbridge University",
      studentId: "NBU-2010-1122",
      status: "alumni",
      degree: "MBBS",
      programme: "Medicine",
      department: "School of Medicine",
      admissionPeriod: "Aug 2005",
      graduationPeriod: "Jul 2010",
      verificationStatus: "institution_verified",
    },
    sharedProfile: {
      consented: true,
      currentTitle: "Consultant Physician",
      currentCompany: "Northlake Health System",
      industry: "Healthcare",
      location: "Chicago, IL",
      credentials: [{ name: "Doctor — Medical Registration", verifiedAt: "2012-01-10" }],
      lastUpdated: "2026-05-02T00:00:00Z",
    },
    credentials: [
      {
        id: "c1",
        name: "MBBS — Degree",
        status: "verified",
        issueDate: "2010-08-01",
        lastUpdated: "2010-08-01",
        history: [{ at: "2010-08-01", label: "Issued" }],
      },
    ],
    verificationActivity: [
      {
        id: "va1",
        requestingOrg: "Northlake Health System",
        date: "2026-07-18",
        result: "In review",
        reviewer: "Daniel Okafor",
        status: "in_progress",
        requestId: "req_002",
      },
    ],
    timeline: [
      { id: "t1", at: "2005-08-01", label: "Person connected to institution" },
      { id: "t2", at: "2010-08-01", label: "Education verified" },
    ],
    lastUpdated: "2026-05-02",
  },
  {
    id: "p_sofia",
    name: "Sofia Marin",
    institutionStatus: "alumni",
    trustStatus: "institution_verified",
    passportStatus: "connected",
    degree: "B.Com (Hons.)",
    graduationYear: "2016",
    relationship: {
      institutionName: "Northbridge University",
      studentId: "NBU-2016-7781",
      status: "alumni",
      degree: "B.Com (Hons.)",
      programme: "Accounting & Finance",
      department: "Northbridge Business School",
      admissionPeriod: "Aug 2013",
      graduationPeriod: "Jun 2016",
      verificationStatus: "institution_verified",
    },
    sharedProfile: {
      consented: true,
      currentTitle: "Senior Auditor",
      currentCompany: "Meridian Audit Partners",
      industry: "Professional Services",
      location: "Toronto, ON",
      credentials: [{ name: "Chartered Accountant", verifiedAt: "2019-11-04" }],
      lastUpdated: "2026-04-18T00:00:00Z",
    },
    credentials: [
      {
        id: "c1",
        name: "B.Com (Hons.) — Degree",
        status: "verified",
        issueDate: "2016-06-30",
        lastUpdated: "2016-06-30",
        history: [{ at: "2016-06-30", label: "Issued" }],
      },
    ],
    verificationActivity: [
      {
        id: "va1",
        requestingOrg: "Meridian Audit Partners",
        date: "2026-07-05",
        result: "Confirmed",
        reviewer: "Priya Menon",
        status: "confirmed",
        requestId: "req_004",
      },
    ],
    timeline: [
      { id: "t1", at: "2013-08-01", label: "Person connected to institution" },
      { id: "t2", at: "2016-06-30", label: "Education verified" },
    ],
    lastUpdated: "2026-04-18",
  },
  {
    id: "p_elena",
    name: "Elena Rossi",
    institutionStatus: "current_student",
    trustStatus: "pending",
    passportStatus: "not_connected",
    degree: "M.Ed.",
    graduationYear: "2027",
    relationship: {
      institutionName: "Northbridge University",
      studentId: "NBU-2025-8823",
      status: "current_student",
      degree: "M.Ed.",
      programme: "Curriculum & Instruction",
      department: "School of Education",
      admissionPeriod: "Aug 2025",
      graduationPeriod: "Expected May 2027",
      verificationStatus: "pending",
    },
    sharedProfile: { consented: false },
    credentials: [],
    verificationActivity: [],
    timeline: [{ id: "t1", at: "2025-08-01", label: "Person connected to institution" }],
    lastUpdated: "2025-08-01",
  },
  {
    id: "p_jonas",
    name: "Jonas Weber",
    institutionStatus: "alumni",
    trustStatus: "disputed",
    passportStatus: "sharing_limited",
    degree: "MBA",
    graduationYear: "2014",
    relationship: {
      institutionName: "Northbridge University",
      studentId: "NBU-2013-0091",
      status: "alumni",
      degree: "MBA",
      programme: "Executive MBA",
      department: "Northbridge Business School",
      admissionPeriod: "Aug 2012",
      graduationPeriod: "May 2014",
      verificationStatus: "disputed",
    },
    sharedProfile: { consented: false },
    credentials: [
      {
        id: "c1",
        name: "Executive MBA — Degree",
        status: "pending",
        issueDate: "—",
        lastUpdated: "2026-07-15",
        history: [{ at: "2026-07-15", label: "Clarification requested" }],
      },
    ],
    verificationActivity: [
      {
        id: "va1",
        requestingOrg: "Atlas Ventures",
        date: "2026-07-14",
        result: "Awaiting clarification",
        reviewer: "Hana Suzuki",
        status: "awaiting_clarification",
        requestId: "req_003",
      },
    ],
    timeline: [
      { id: "t1", at: "2012-08-01", label: "Person connected to institution" },
      { id: "t2", at: "2026-07-15", label: "Clarification requested" },
    ],
    lastUpdated: "2026-07-15",
  },
  {
    id: "p_ravi",
    name: "Ravi Kulkarni",
    institutionStatus: "withdrawn",
    trustStatus: "revoked",
    passportStatus: "connected",
    degree: "M.Tech Computer Science",
    graduationYear: "—",
    relationship: {
      institutionName: "Northbridge University",
      studentId: "NBU-2014-3320",
      status: "withdrawn",
      degree: "M.Tech Computer Science",
      programme: "Computer Science",
      department: "School of Engineering",
      admissionPeriod: "Aug 2012",
      graduationPeriod: "—",
      verificationStatus: "revoked",
    },
    sharedProfile: {
      consented: true,
      currentTitle: "Software Engineer",
      currentCompany: "Trellis Consulting",
      industry: "Technology",
      location: "Pune, IN",
      credentials: [],
      lastUpdated: "2026-03-11T00:00:00Z",
    },
    credentials: [
      {
        id: "c1",
        name: "M.Tech Computer Science — Degree",
        status: "revoked",
        issueDate: "—",
        lastUpdated: "2026-06-29",
        history: [
          { at: "2014-05-10", label: "Withdrawn from programme" },
          { at: "2026-06-29", label: "Revoked" },
        ],
        revokedReason: "Programme not completed; withdrawal on record.",
      },
    ],
    verificationActivity: [
      {
        id: "va1",
        requestingOrg: "Trellis Consulting",
        date: "2026-06-28",
        result: "Discrepancy reported",
        reviewer: "Daniel Okafor",
        status: "discrepancy",
        requestId: "req_005",
      },
    ],
    timeline: [
      { id: "t1", at: "2012-08-01", label: "Person connected to institution" },
      { id: "t2", at: "2014-05-10", label: "Withdrawn from programme" },
      { id: "t3", at: "2026-06-29", label: "Credential revoked" },
    ],
    lastUpdated: "2026-06-29",
  },
];

export const mockSettings: InstitutionSettings = {
  institution: mockInstitution,
  account: {
    fullName: "Priya Menon",
    email: "priya.menon@northbridge.edu",
    phone: "+1 555 010 4421",
    currentRole: "Registrar",
    location: "Northbridge, NB",
    emailVerifiedAt: "2026-07-10T10:00:00Z",
    phoneVerifiedAt: null,
  },
  notifications: [
    {
      id: "pref_invites",
      eventType: "trust_invitation_created",
      label: "Trust invitation",
      description: "Notifications about Trust Invitations relevant to your institution.",
      enabled: true,
      preferredChannels: ["email"],
      required: false,
    },
    {
      id: "pref_verifications",
      eventType: "verification_completed",
      label: "Verification completed",
      description: "Notifications when a verification request reaches a final resolution.",
      enabled: true,
      preferredChannels: ["email"],
      required: false,
    },
    {
      id: "pref_password_reset",
      eventType: "password_reset_requested",
      label: "Password reset requested",
      description: "Security notifications for password reset requests.",
      enabled: true,
      preferredChannels: ["email"],
      required: true,
    },
  ],
  sessions: [
    {
      id: "s1",
      createdAt: "2026-07-20T08:00:00Z",
      expiresAt: "2026-08-20T08:00:00Z",
      lastActiveAt: "2026-07-26T09:30:00Z",
      current: true,
      device: "MacBook Pro — Chrome",
      location: "Northbridge, NB",
    },
    {
      id: "s2",
      createdAt: "2026-07-18T07:00:00Z",
      expiresAt: "2026-08-18T07:00:00Z",
      lastActiveAt: "2026-07-24T21:14:00Z",
      current: false,
      device: "iPhone — Safari",
      location: "Northbridge, NB",
    },
  ],
  security: {
    domainVerified: true,
    domainVerifiedAt: "2026-07-15T09:00:00Z",
    canChangePassword: true,
  },
  workspace: {
    verificationPreferencesAvailable: false,
    integrationConnectionsAvailable: false,
    sessionDeviceDetailsAvailable: true,
    mfaAvailable: false,
    securityHistoryAvailable: false,
  },
};

export const mockMagicLinks: Record<string, MagicLinkRequest> = {
  "valid-token": {
    token: "valid-token",
    state: "valid",
    expiresAt: "2026-07-30T00:00:00Z",
    request: {
      reference: "KVR-2026-0499",
      requestedBy: "Beacon Partners",
      purpose: "Employment verification — Associate",
      requestDate: "2026-07-22T09:00:00Z",
      consentReceived: true,
      candidate: {
        candidateName: "Nora Chen",
        studentId: "NBU-2019-2210",
        institutionName: "Northbridge University",
        degree: "B.A. Economics",
        programme: "Economics",
        department: "School of Social Sciences",
        admissionYear: "2016",
        graduationYear: "2019",
        completionStatus: "Completed",
      },
      evidence: [
        {
          id: "e1",
          name: "Degree_Certificate.pdf",
          type: "Degree certificate",
          uploadedBy: "Nora Chen",
          uploadedAt: "2026-07-22T09:00:00Z",
        },
      ],
    },
  },
  "expired-token": { token: "expired-token", state: "expired", expiresAt: "2026-07-01T00:00:00Z" },
  "completed-token": { token: "completed-token", state: "completed" },
  "revoked-token": { token: "revoked-token", state: "revoked" },
};
