/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionRouteImport } from './routes/institution'
import { Route as InstitutionIndexRouteImport } from './routes/institution.index'
import { Route as InstitutionLoginRouteImport } from './routes/institution.login'
import { Route as InstitutionSettingsRouteImport } from './routes/institution.settings'
import { Route as InstitutionTeamRouteImport } from './routes/institution.team'
import { Route as InstitutionPeopleIndexRouteImport } from './routes/institution.people.index'
import { Route as InstitutionPeoplePersonIdRouteImport } from './routes/institution.people.$personId'
import { Route as InstitutionSignupIndexRouteImport } from './routes/institution.signup.index'
import { Route as InstitutionSignupAdminRouteImport } from './routes/institution.signup.admin'
import { Route as InstitutionSignupInstitutionRouteImport } from './routes/institution.signup.institution'
import { Route as InstitutionSignupReviewRouteImport } from './routes/institution.signup.review'
import { Route as InstitutionSignupSuccessRouteImport } from './routes/institution.signup.success'
import { Route as InstitutionSignupVerifyRouteImport } from './routes/institution.signup.verify'
import { Route as InstitutionVerificationsIndexRouteImport } from './routes/institution.verifications.index'
import { Route as InstitutionVerificationsRequestIdRouteImport } from './routes/institution.verifications.$requestId'
import { Route as InstitutionVerifyTokenRouteImport } from './routes/institution.verify.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRoute = InstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionIndexRoute = InstitutionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionLoginRoute = InstitutionLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionSettingsRoute = InstitutionSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionTeamRoute = InstitutionTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionPeopleIndexRoute = InstitutionPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionPeoplePersonIdRoute =
  InstitutionPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionSignupIndexRoute = InstitutionSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionSignupAdminRoute = InstitutionSignupAdminRouteImport.update({
  id: '/signup/admin',
  path: '/signup/admin',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionSignupInstitutionRoute =
  InstitutionSignupInstitutionRouteImport.update({
    id: '/signup/institution',
    path: '/signup/institution',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionSignupReviewRoute = InstitutionSignupReviewRouteImport.update({
  id: '/signup/review',
  path: '/signup/review',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionSignupSuccessRoute =
  InstitutionSignupSuccessRouteImport.update({
    id: '/signup/success',
    path: '/signup/success',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionSignupVerifyRoute = InstitutionSignupVerifyRouteImport.update({
  id: '/signup/verify',
  path: '/signup/verify',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionVerificationsIndexRoute =
  InstitutionVerificationsIndexRouteImport.update({
    id: '/verifications/',
    path: '/verifications/',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionVerificationsRequestIdRoute =
  InstitutionVerificationsRequestIdRouteImport.update({
    id: '/verifications/$requestId',
    path: '/verifications/$requestId',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionVerifyTokenRoute = InstitutionVerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => InstitutionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/institution/login': typeof InstitutionLoginRoute
  '/institution/settings': typeof InstitutionSettingsRoute
  '/institution/team': typeof InstitutionTeamRoute
  '/institution/': typeof InstitutionIndexRoute
  '/institution/people/$personId': typeof InstitutionPeoplePersonIdRoute
  '/institution/signup/admin': typeof InstitutionSignupAdminRoute
  '/institution/signup/institution': typeof InstitutionSignupInstitutionRoute
  '/institution/signup/review': typeof InstitutionSignupReviewRoute
  '/institution/signup/success': typeof InstitutionSignupSuccessRoute
  '/institution/signup/verify': typeof InstitutionSignupVerifyRoute
  '/institution/verifications/$requestId': typeof InstitutionVerificationsRequestIdRoute
  '/institution/verify/$token': typeof InstitutionVerifyTokenRoute
  '/institution/people/': typeof InstitutionPeopleIndexRoute
  '/institution/signup/': typeof InstitutionSignupIndexRoute
  '/institution/verifications/': typeof InstitutionVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institution/login': typeof InstitutionLoginRoute
  '/institution/settings': typeof InstitutionSettingsRoute
  '/institution/team': typeof InstitutionTeamRoute
  '/institution': typeof InstitutionIndexRoute
  '/institution/people/$personId': typeof InstitutionPeoplePersonIdRoute
  '/institution/signup/admin': typeof InstitutionSignupAdminRoute
  '/institution/signup/institution': typeof InstitutionSignupInstitutionRoute
  '/institution/signup/review': typeof InstitutionSignupReviewRoute
  '/institution/signup/success': typeof InstitutionSignupSuccessRoute
  '/institution/signup/verify': typeof InstitutionSignupVerifyRoute
  '/institution/verifications/$requestId': typeof InstitutionVerificationsRequestIdRoute
  '/institution/verify/$token': typeof InstitutionVerifyTokenRoute
  '/institution/people': typeof InstitutionPeopleIndexRoute
  '/institution/signup': typeof InstitutionSignupIndexRoute
  '/institution/verifications': typeof InstitutionVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/institution/login': typeof InstitutionLoginRoute
  '/institution/settings': typeof InstitutionSettingsRoute
  '/institution/team': typeof InstitutionTeamRoute
  '/institution/': typeof InstitutionIndexRoute
  '/institution/people/$personId': typeof InstitutionPeoplePersonIdRoute
  '/institution/signup/admin': typeof InstitutionSignupAdminRoute
  '/institution/signup/institution': typeof InstitutionSignupInstitutionRoute
  '/institution/signup/review': typeof InstitutionSignupReviewRoute
  '/institution/signup/success': typeof InstitutionSignupSuccessRoute
  '/institution/signup/verify': typeof InstitutionSignupVerifyRoute
  '/institution/verifications/$requestId': typeof InstitutionVerificationsRequestIdRoute
  '/institution/verify/$token': typeof InstitutionVerifyTokenRoute
  '/institution/people/': typeof InstitutionPeopleIndexRoute
  '/institution/signup/': typeof InstitutionSignupIndexRoute
  '/institution/verifications/': typeof InstitutionVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/institution'
    | '/institution/login'
    | '/institution/settings'
    | '/institution/team'
    | '/institution/'
    | '/institution/people/$personId'
    | '/institution/signup/admin'
    | '/institution/signup/institution'
    | '/institution/signup/review'
    | '/institution/signup/success'
    | '/institution/signup/verify'
    | '/institution/verifications/$requestId'
    | '/institution/verify/$token'
    | '/institution/people/'
    | '/institution/signup/'
    | '/institution/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institution/login'
    | '/institution/settings'
    | '/institution/team'
    | '/institution'
    | '/institution/people/$personId'
    | '/institution/signup/admin'
    | '/institution/signup/institution'
    | '/institution/signup/review'
    | '/institution/signup/success'
    | '/institution/signup/verify'
    | '/institution/verifications/$requestId'
    | '/institution/verify/$token'
    | '/institution/people'
    | '/institution/signup'
    | '/institution/verifications'
  id:
    | '__root__'
    | '/'
    | '/institution'
    | '/institution/login'
    | '/institution/settings'
    | '/institution/team'
    | '/institution/'
    | '/institution/people/$personId'
    | '/institution/signup/admin'
    | '/institution/signup/institution'
    | '/institution/signup/review'
    | '/institution/signup/success'
    | '/institution/signup/verify'
    | '/institution/verifications/$requestId'
    | '/institution/verify/$token'
    | '/institution/people/'
    | '/institution/signup/'
    | '/institution/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstitutionRoute: typeof InstitutionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution': {
      id: '/institution'
      path: '/institution'
      fullPath: '/institution'
      preLoaderRoute: typeof InstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/': {
      id: '/institution/'
      path: '/'
      fullPath: '/institution/'
      preLoaderRoute: typeof InstitutionIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/login': {
      id: '/institution/login'
      path: '/login'
      fullPath: '/institution/login'
      preLoaderRoute: typeof InstitutionLoginRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/settings': {
      id: '/institution/settings'
      path: '/settings'
      fullPath: '/institution/settings'
      preLoaderRoute: typeof InstitutionSettingsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/team': {
      id: '/institution/team'
      path: '/team'
      fullPath: '/institution/team'
      preLoaderRoute: typeof InstitutionTeamRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/people/': {
      id: '/institution/people/'
      path: '/people'
      fullPath: '/institution/people/'
      preLoaderRoute: typeof InstitutionPeopleIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/people/$personId': {
      id: '/institution/people/$personId'
      path: '/people/$personId'
      fullPath: '/institution/people/$personId'
      preLoaderRoute: typeof InstitutionPeoplePersonIdRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/signup/': {
      id: '/institution/signup/'
      path: '/signup'
      fullPath: '/institution/signup/'
      preLoaderRoute: typeof InstitutionSignupIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/signup/admin': {
      id: '/institution/signup/admin'
      path: '/signup/admin'
      fullPath: '/institution/signup/admin'
      preLoaderRoute: typeof InstitutionSignupAdminRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/signup/institution': {
      id: '/institution/signup/institution'
      path: '/signup/institution'
      fullPath: '/institution/signup/institution'
      preLoaderRoute: typeof InstitutionSignupInstitutionRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/signup/review': {
      id: '/institution/signup/review'
      path: '/signup/review'
      fullPath: '/institution/signup/review'
      preLoaderRoute: typeof InstitutionSignupReviewRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/signup/success': {
      id: '/institution/signup/success'
      path: '/signup/success'
      fullPath: '/institution/signup/success'
      preLoaderRoute: typeof InstitutionSignupSuccessRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/signup/verify': {
      id: '/institution/signup/verify'
      path: '/signup/verify'
      fullPath: '/institution/signup/verify'
      preLoaderRoute: typeof InstitutionSignupVerifyRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/verifications/': {
      id: '/institution/verifications/'
      path: '/verifications'
      fullPath: '/institution/verifications/'
      preLoaderRoute: typeof InstitutionVerificationsIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/verifications/$requestId': {
      id: '/institution/verifications/$requestId'
      path: '/verifications/$requestId'
      fullPath: '/institution/verifications/$requestId'
      preLoaderRoute: typeof InstitutionVerificationsRequestIdRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/verify/$token': {
      id: '/institution/verify/$token'
      path: '/verify/$token'
      fullPath: '/institution/verify/$token'
      preLoaderRoute: typeof InstitutionVerifyTokenRouteImport
      parentRoute: typeof InstitutionRoute
    }
  }
}

interface InstitutionRouteChildren {
  InstitutionLoginRoute: typeof InstitutionLoginRoute
  InstitutionSettingsRoute: typeof InstitutionSettingsRoute
  InstitutionTeamRoute: typeof InstitutionTeamRoute
  InstitutionIndexRoute: typeof InstitutionIndexRoute
  InstitutionPeoplePersonIdRoute: typeof InstitutionPeoplePersonIdRoute
  InstitutionSignupAdminRoute: typeof InstitutionSignupAdminRoute
  InstitutionSignupInstitutionRoute: typeof InstitutionSignupInstitutionRoute
  InstitutionSignupReviewRoute: typeof InstitutionSignupReviewRoute
  InstitutionSignupSuccessRoute: typeof InstitutionSignupSuccessRoute
  InstitutionSignupVerifyRoute: typeof InstitutionSignupVerifyRoute
  InstitutionVerificationsRequestIdRoute: typeof InstitutionVerificationsRequestIdRoute
  InstitutionVerifyTokenRoute: typeof InstitutionVerifyTokenRoute
  InstitutionPeopleIndexRoute: typeof InstitutionPeopleIndexRoute
  InstitutionSignupIndexRoute: typeof InstitutionSignupIndexRoute
  InstitutionVerificationsIndexRoute: typeof InstitutionVerificationsIndexRoute
}

const InstitutionRouteChildren: InstitutionRouteChildren = {
  InstitutionLoginRoute: InstitutionLoginRoute,
  InstitutionSettingsRoute: InstitutionSettingsRoute,
  InstitutionTeamRoute: InstitutionTeamRoute,
  InstitutionIndexRoute: InstitutionIndexRoute,
  InstitutionPeoplePersonIdRoute: InstitutionPeoplePersonIdRoute,
  InstitutionSignupAdminRoute: InstitutionSignupAdminRoute,
  InstitutionSignupInstitutionRoute: InstitutionSignupInstitutionRoute,
  InstitutionSignupReviewRoute: InstitutionSignupReviewRoute,
  InstitutionSignupSuccessRoute: InstitutionSignupSuccessRoute,
  InstitutionSignupVerifyRoute: InstitutionSignupVerifyRoute,
  InstitutionVerificationsRequestIdRoute:
    InstitutionVerificationsRequestIdRoute,
  InstitutionVerifyTokenRoute: InstitutionVerifyTokenRoute,
  InstitutionPeopleIndexRoute: InstitutionPeopleIndexRoute,
  InstitutionSignupIndexRoute: InstitutionSignupIndexRoute,
  InstitutionVerificationsIndexRoute: InstitutionVerificationsIndexRoute,
}

const InstitutionRouteWithChildren = InstitutionRoute._addFileChildren(
  InstitutionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstitutionRoute: InstitutionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
